### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by tomhumbert** [Ejhfast/empath-client#12]
If I try using Empath, it now says:

<html>
  <head>
    <title>500 Internal Server Error</title>
  </head>
  <body>
    <h1>500 Internal Server Error</h1>
    Server got itself in trouble
  </body>
</html>

**Comment by senthilchandrasegaran** [comment]
Yes, I have the same issue. The project page (http://empath.stanford.edu/) also does not seem to be available anymore.

**Comment by laols574** [comment]
HI TOM, I'm having the same problem :D

**Comment by Ejhfast** [comment]
Fixed!

**Comment by paulcbogdan** [comment]
The server appears to be down again
