### ISSUE TITLE
ImportError when importing empath

### ISSUE THREAD

**Issue by athersharif** [Ejhfast/empath-client#6]
as per the README:

```
from empath import Empath
lexicon = Empath()
```

doing this gives the error:

```
Traceback (most recent call last):
  File "empath.py", line 1, in <module>
    from empath import Empath
  File "[file-path-of-the-python-file]", line 1, in <module>
    from empath import Empath
ImportError: cannot import name 'Empath' from 'empath' ([file-path-of-the-python-file]
```

also tried:

```
import empath
lexicon = empath.Empath()
```

which gives the error:

```
AttributeError: module 'empath' has no attribute 'Empath'
```

any insights on how to navigate around this? seeing this on both python 2 and 3.

**Comment by kimberlycas** [comment]
The problem is that your file is called empath.py. So python is looking for Empath in that file, instead the real package.
Simply rename your file and it should work fine.

**Comment by athersharif** [comment]
ah you're right! thanks @kimberlycas! worked like a charm.

closing this issue.
